apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-images.yml
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: haproxy
  name: haproxy
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  - name: "8082"
    port: 8082
    targetPort: 8082
  - name: "8140"
    port: 8140
    targetPort: 8140
  - name: "9000"
    port: 9000
    targetPort: 9000
  selector:
    io.kompose.service: haproxy
status:
  loadBalancer: {}
