apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-images.yml
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: nats
  name: nats
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nats
    spec:
      containers:
      - image: vshn/puppet-nats
        name: nats
        ports:
        - containerPort: 4222
        resources: {}
        volumeMounts:
        - mountPath: /etc/nats/ssl
          name: nats-ssl
      restartPolicy: Always
      volumes:
      - name: nats-ssl
        persistentVolumeClaim:
          claimName: nats-ssl
status: {}
