apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-images.yml
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: nats
  name: nats
  namespace: puppetstack
spec:
  ports:
  - name: "4222"
    port: 4222
    targetPort: 4222
  selector:
    io.kompose.service: nats
status:
  loadBalancer: {}
