apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-images.yml
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: puppetexplorer
  name: puppetexplorer
  namespace: puppetstack
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: puppetexplorer
    spec:
      containers:
      - env:
        - name: PUPPETDB_SERVER
          value: puppetdb.puppetstack
        image: vshn/puppet-puppetexplorer
        name: puppetexplorer
        resources: {}
      restartPolicy: Always
status: {}
