apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-images.yml
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: puppetdb
  name: puppetdb
  namespace: puppetstack
spec:
  type: LoadBalancer
  ports:
  - name: puppetdb
    protocol: "TCP"
    port: 8080
    targetPort: 8080
  - name: puppetdbapi
    protocol: "TCP"
    port: 8081
    targetPort: 8081
  selector:
    io.kompose.service: puppetdb
status:
  loadBalancer: {}
